### ISSUE TITLE
Capturing not working with addEventHard

### ISSUE THREAD

**Issue by MitMaro** [bevacqua/crossvent#2]
[attachEvent](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/removeEventListener) only takes two parameters (event name, function).

In commit 0c6a5a9fefb169d21a2ad80401bd2b1ff323b642 capturing was added as a third parameter to attachEvent and I believe it has no effect. I don't have a windows computer to test this in Internet Explorer, but I think [setCapture](https://msdn.microsoft.com/en-us/library/ie/ms536742%28v=vs.85%29.aspx) is the solution.

**Comment by bevacqua** [comment]
Fixed in `1.3.0`
