### ISSUE TITLE
All errors / console messages / debugger calls sent through crossvent

### ISSUE THREAD

**Issue by benjamin-smith** [bevacqua/crossvent#3]
When using Dragula on a web project, all errors appear to be "routed" through `crossvent.js`. This includes,
- `debugger;` statements
- breakpoints added via Dev Tools
- uncaught exceptions _in any JS file_

All of these stops point to the last line of `crossvent.js`. Any idea why this is happening, or how I can avoid this?

Let me know if I should move this to the Dragula issue tracker.

Chrome Version 43.0.2357.132 (64-bit) on OSX 10.10.3.

**Comment by bevacqua** [comment]
See https://github.com/bevacqua/dragula/issues/102. You should be able to step over that module, or at the very least expand the stack trace

**Comment by benjamin-smith** [comment]
Thank you!
