### ISSUE TITLE
Webpack: Illegal return statement

### ISSUE THREAD

**Issue by KaiHufenbach** [bevacqua/crossvent#4]
Hi,

thanks for the awesome work!

Just updated to the latest version of dragula (incl. crossvent) and got problems using webpack:

![image](https://cloud.githubusercontent.com/assets/959063/9453874/f13c059c-4abd-11e5-965e-a315a111cc6c.png)

changeing:

crossvent.js:6-8

```
if (!doc) {
  return;
}
```

to IIFE:

```
(function (){if (!doc) {
  return;
}}());
```

should solve the problem!

**Comment by bevacqua** [comment]
Fixed in latest

**Comment by bevacqua** [comment]
Thanks for reporting!
